name: Generate Datas

on: push
  schedule: # execute every 5h30 hours
    - cron: '30 5 * * 1,3'
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: windows-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MarianaSiano
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
